# wget http://classroom/materials/hosts.j2 
# wget http://classroom/materials/hosts.yml 
# vim hosts.j2
{% for i in groups.all %}
{{ hostvars[i].ansible_facts.default_ipv4.address }} {{ hostvars[i].ansible_facts.nodename }} {{ hostvars[i].ansible_facts.hostname }}
{% endfor %}

# vim hosts.yml
---
- name: gen host file
  hosts: all
  tasks: 
  - name: Template a file to /etc/myhosts
    template:
      src: /home/greg/ansible/hosts.j2
      dest: /etc/myhosts
    when: inventory_hostname in groups.dev

# ansible-navigator run hosts.yml -m stdout
# ansible dev -m shell -a 'cat /etc/myhosts'