# vim /home/greg/ansible/lv.yml
---
- name: Create LVM
  hosts: all
  tasks:
    - block:
      - name: lv 1500M
        community.general.lvol:
          vg: research
          lv: data
          size: 1500
      - name: Create ext4
        community.general.filesystem:
          fstype: ext4
          dev: /dev/research/data
    
      rescue:
      - name: Coud not Creat lvm
        ansible.builtin.debug:
          msg: Could not create logical volume of that size
      - name: lv 800 M
        community.general.lvol:
          vg: research
          lv: data
          size: 800
      - name: Creat ext4
        community.general.filesystem:
          fstype: ext4
          dev: /dev/research/data
      when: ansible_lvm.vgs.research is not defined
  - debug:
      msg: Volume group done not exist
    when: ansible_lvm.vgs.research is not defined

# ansible-navigator run /home/greg/ansible/lv.yml -m stdout
# ansible all -m shell -a 'lvscan'
# ansible all -m shell -a 'blikid /dev/research/data'
